### ISSUE TITLE
Calling ::root() on a local site alias with no root will return a path

### ISSUE THREAD

**Issue by q0rban** [consolidation/site-alias#8]
### Steps to reproduce

Disclaimer: I'm using drush, but I think this is a site-alias issue.

**Describe the bug**

Consider an alias as follows:

`drush/sites/example.site.yml`
```yml
common:
  paths:
    - files: sites/example.com/files

prod:
  uri: example.com

local:
  uri: example.local
  root: /app/web
```
Let's say you then call `drush @example my-command`. Note the lack of `.prod` or `.local`. And inside of that drush command you have:

```php
$alias = Drush::aliasManager()->getSelf();
$alias->root();
```  

**Expected behavior**

I would expect `$alias->root()` to be `null`.

**Actual behavior**
It returned the composer root (not the Drupal root).

**Workaround**
The workaround is to be sure you use specific aliases.
